[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@yearnvaults/=lib/yearn-vaults/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    "@uniswap/=lib/v3-core/"
]
fs_permissions = [{ access = "read", path = "./artifacts"}]
gas_reports = ["BalancerTripod"]
# See more config options https://github.com/gakonst/foundry/tree/master/config
